In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [2]:
import sys
#change the directory where you store the data
TD_DIR =  '/content/drive/My Drive/ROB311/TP6/'
sys.path.append(TD_DIR)

read train data

In [62]:
import numpy as np

#read the data
with open(TD_DIR+'optdigits.tra', encoding='utf-8') as f:
  original_data = f.read().split('\n')
  for i in range(len(original_data)):
    original_data[i] = original_data[i].split(',')
#print(original_data)

train_data = np.array([[original_data[row][col] for col in range(len(original_data[0])-1)] for row in range(len(original_data)-1)], dtype=int)
train_label = np.array([original_data[row][64] for row in range(len(original_data)-1)], dtype=int)

from sklearn.cluster import KMeans
from sklearn.decomposition import PCA
from sklearn.pipeline import make_pipeline
pca = PCA(n_components=55, whiten=True)
kmeans = KMeans(n_clusters=10, random_state=42)
model = make_pipeline(pca, kmeans)

model.fit(train_data)
kmeans.fit(train_data)

KMeans(algorithm='auto', copy_x=True, init='k-means++', max_iter=300,
       n_clusters=10, n_init=10, n_jobs=None, precompute_distances='auto',
       random_state=42, tol=0.0001, verbose=0)

read test data

In [63]:
import numpy as np

#read the data
with open(TD_DIR+'optdigits.tes', encoding='utf-8') as f:
  original_data = f.read().split('\n')
  for i in range(len(original_data)):
    original_data[i] = original_data[i].split(',')

test_data = np.array([[original_data[row][col] for col in range(len(original_data[0])-1)] for row in range(len(original_data)-1)], dtype=int)
test_label = np.array([original_data[row][64] for row in range(len(original_data)-1)], dtype=int)

##predict_label = model.predict(test_data)
predict_label = kmeans.predict(test_data)

get the transform relation between test label and predict label

In [64]:
'''
count = np.array([0,0,0,0,0,0,0,0,0,0])
transform = np.array([0,0,0,0,0,0,0,0,0,0])
for i in range(10):
  count = np.array([0,0,0,0,0,0,0,0,0,0])
  for j in range(len(predict_label)):
    if i == test_label[j]:
      count[predict_label[j]] = count[predict_label[j]] + 1
  max = count[0]
  print(count)
  index = 0
  used = []
  for j in range(10):
    if ((max < count[j])):
      index = j
      max = count[j]
  transform[i] = index
print(transform)

'''
count = np.array([0,0,0,0,0,0,0,0,0,0])
transform = np.array([0,0,0,0,0,0,0,0,0,0])
for i in range(10):
  count = np.array([0,0,0,0,0,0,0,0,0,0])
  for j in range(len(test_label)):
    if i == predict_label[j]:
      count[test_label[j]] = count[test_label[j]] + 1
  max = count[0]
  print(count)
  index = 0
  used = []
  for j in range(10):
    if ((max < count[j])):
      index = j
      max = count[j]
  transform[i] = index
print(transform)


[  0  21 149   0   0   0   0   0   1   0]
[  0   1   9 164   0  26   0   0  10 145]
[  2   0   0   0 159   1   0   1   0   0]
[176   0   1   0   0   0   1   0   0   0]
[  0   3   0   0   0   1 175   0   1   0]
[  0   0   4  10   7   0   0 166   1   4]
[ 0 52  2  0  4  1  0  8  8 24]
[  0   0  10   6   5   0   1   3 131   3]
[  0   1   0   2   0 153   0   1   2   4]
[  0 104   2   1   6   0   4   0  20   0]
[2 3 4 0 6 7 1 8 5 1]


In [65]:
transform[9] = 9
print(transform)
for i in range(len(test_label)):
  for j in range(10):
    if test_label[i] == transform[j]:
      test_label[i] = j

[2 3 4 0 6 7 1 8 5 9]


In [66]:
right = 0
wrong = 0
for i in range(len(predict_label)):
  if predict_label[i] == test_label[i]:
    right = right + 1
  else:
    wrong = wrong + 1
print(right/len(predict_label))
print(wrong/len(predict_label))

0.47189760712298273
0.5281023928770172
